### ISSUE TITLE
Classe Cliente

### ISSUE THREAD

**Issue by profRenatoOliveira1** [RafaelaGusmao/projeto-3#1]
Rafaela, é necessário fazer alguns ajustes na sua classe

1. Faltam comentários no padrão que utilizamos na classe Carro;
2. No construtor, não deve ter idCliente. Em uma situação onde vamos cadastrar um novo cliente, não vamos ter essa informação para passar para o construtor, pois esse ID vai ser gerado só no banco de dados;
3. Faltou implementar os métodos get e set;
4. Não é necessário implementar os métodos que estão no diagrama de classes ainda, vamos fazer isso em futuras atualizações, portanto remova esses métodos.

Qualquer dúvida me procure.

**Comment by RafaelaGusmao** [comment]
mudanças feitas, acho que foi certo

**Comment by profRenatoOliveira1** [comment]
Muito bom.
